### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::bindShared()

### ISSUE THREAD

**Issue by obayesshelton** [tjphippen/docusign#6]
```
ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Foundation\Application::bindShared() in /var/www/api/vendor/tjphippen/docusign/src/DocusignServiceProvider.php:19
Stack trace:
#0 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(554): Tjphippen\Docusign\DocusignServiceProvider->register()
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(671): Illuminate\Foundation\Application->register(Object(Tjphippen\Docusign\DocusignServiceProvider))
#2 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(651): Illuminate\Foundation\Application->registerDeferredProvider('Tjphippen\\Docus...', 'docusign')
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(627): Illuminate\Foundation\Application->loadDeferredProvider('docusign')
#4 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(225): Illuminate\Foundation\Application->loadDeferredProviders()
#5 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#6 /var/www/api/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}
```

**Comment by ouladck** [comment]
Change `bindShared()` to `singleton()` in `vendor/tjphippen/docusign/src/DocusignServiceProvider.php`

**Comment by tjphippen** [comment]
karim88 is right, bindShared was deprecated & this fix will be pushed shortly.
